package com.jeecms.cms.entity.main.base;

import java.util.Date;

import com.jeecms.cms.entity.main.Notarization;

// default package
// Generated 2014-9-13 12:13:32 by Hibernate Tools 3.4.0.CR1

/**
 * Notarization generated by hbm2java
 */
public class BaseNotzResult implements java.io.Serializable {

	
	private int hashCode = Integer.MIN_VALUE;
	private Integer id;
	private String result;
	private String name;
	private String tel;
	private String email;
	private Integer status;
	private Integer siteId;
	private Date createDate;

	public Integer getId() {
		return id;
	}





	public void setId(Integer id) {
		this.id = id;
	}





	public String getResult() {
		return result;
	}





	public void setResult(String result) {
		this.result = result;
	}





	public String getName() {
		return name;
	}





	public void setName(String name) {
		this.name = name;
	}





	public String getTel() {
		return tel;
	}





	public void setTel(String tel) {
		this.tel = tel;
	}





	public String getEmail() {
		return email;
	}





	public void setEmail(String email) {
		this.email = email;
	}




	public Integer getStatus() {
		return status;
	}





	public void setStatus(Integer status) {
		this.status = status;
	}





	public Integer getSiteId() {
		return siteId;
	}





	public void setSiteId(Integer siteId) {
		this.siteId = siteId;
	}





	public Date getCreateDate() {
		return createDate;
	}





	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}





	public String toString () {
		return super.toString();
	}
}
