package com.jeecms.cms.entity.main.base;

import com.jeecms.cms.entity.main.Notarization;

// default package
// Generated 2014-9-13 12:13:32 by Hibernate Tools 3.4.0.CR1

/**
 * Notarization generated by hbm2java
 */
public class BaseNotarization implements java.io.Serializable {

	
	private int hashCode = Integer.MIN_VALUE;
	private Integer id;
	private String title;
	private String resultPage;
	private String formater;
	private Integer type;
	private Integer category;
	private Integer position;
	private Integer siteId;
	private Notarization next;
	private Integer nextId;
	private Notarization preview;
	private Integer priority;
	private String name1;
	private String name2;
	private String value1;
	private String value2;
	
	private String q1;
	private String q2;
	private String q3;
	private String q4;
	private String q5;
	private String q6;
	private String q7;
	private String q8;
	
	private String r1;
	private String r2;
	private String r3;
	private String r4;
	private String r5;
	private String r6;
	private String r7;
	private String r8;
	
	private Notarization n1;
	private Notarization n2;
	private Notarization n3;
	private Notarization n4;
	private Notarization n5;
	private Notarization n6;
	private Notarization n7;
	private Notarization n8;

	public BaseNotarization() {
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}
	
	public String getResultPage() {
		return resultPage;
	}

	public void setResultPage(String resultPage) {
		this.resultPage = resultPage;
	}

	public String getFormater() {
		return this.formater;
	}

	public void setFormater(String formater) {
		this.formater = formater;
	}

	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	public String getName1() {
		return this.name1;
	}

	public void setName1(String name1) {
		this.name1 = name1;
	}

	public String getName2() {
		return this.name2;
	}

	public void setName2(String name2) {
		this.name2 = name2;
	}

	public String getValue1() {
		return this.value1;
	}

	public void setValue1(String value1) {
		this.value1 = value1;
	}

	public String getValue2() {
		return this.value2;
	}

	public void setValue2(String value2) {
		this.value2 = value2;
	}

	public String getQ1() {
		return this.q1;
	}

	public void setQ1(String q1) {
		this.q1 = q1;
	}

	public String getQ2() {
		return this.q2;
	}

	public void setQ2(String q2) {
		this.q2 = q2;
	}

	public String getQ3() {
		return this.q3;
	}

	public void setQ3(String q3) {
		this.q3 = q3;
	}

	public String getQ4() {
		return this.q4;
	}

	public void setQ4(String q4) {
		this.q4 = q4;
	}

	public String getQ5() {
		return this.q5;
	}

	public void setQ5(String q5) {
		this.q5 = q5;
	}

	public String getQ6() {
		return this.q6;
	}

	public void setQ6(String q6) {
		this.q6 = q6;
	}

	public String getQ7() {
		return this.q7;
	}

	public void setQ7(String q7) {
		this.q7 = q7;
	}

	public String getQ8() {
		return this.q8;
	}

	public void setQ8(String q8) {
		this.q8 = q8;
	}

	public String getR1() {
		return this.r1;
	}

	public void setR1(String r1) {
		this.r1 = r1;
	}

	public String getR2() {
		return this.r2;
	}

	public void setR2(String r2) {
		this.r2 = r2;
	}

	public String getR3() {
		return this.r3;
	}

	public void setR3(String r3) {
		this.r3 = r3;
	}

	public String getR4() {
		return this.r4;
	}

	public void setR4(String r4) {
		this.r4 = r4;
	}

	public String getR5() {
		return this.r5;
	}

	public void setR5(String r5) {
		this.r5 = r5;
	}

	public String getR6() {
		return this.r6;
	}

	public void setR6(String r6) {
		this.r6 = r6;
	}

	public String getR7() {
		return this.r7;
	}

	public void setR7(String r7) {
		this.r7 = r7;
	}

	public String getR8() {
		return this.r8;
	}

	public void setR8(String r8) {
		this.r8 = r8;
	}

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Integer getCategory() {
		return category;
	}

	public void setCategory(Integer category) {
		this.category = category;
	}

	public Integer getPosition() {
		return position;
	}

	public void setPosition(Integer position) {
		this.position = position;
	}

	public Integer getSiteId() {
		return siteId;
	}

	public void setSiteId(Integer siteId) {
		this.siteId = siteId;
	}

	public Notarization getNext() {
		return next;
	}

	public void setNext(Notarization next) {
		this.next = next;
	}

	public Integer getNextId() {
		if(next==null){
			nextId =0;
		}else{
			nextId = next.getId();
		}
		return nextId;
	}

	public Notarization getPreview() {
		return preview;
	}

	public void setPreview(Notarization preview) {
		this.preview = preview;
	}

	public Notarization getN1() {
		return n1;
	}

	public void setN1(Notarization n1) {
		this.n1 = n1;
	}

	public Notarization getN2() {
		return n2;
	}

	public void setN2(Notarization n2) {
		this.n2 = n2;
	}

	public Notarization getN3() {
		return n3;
	}

	public void setN3(Notarization n3) {
		this.n3 = n3;
	}

	public Notarization getN4() {
		return n4;
	}

	public void setN4(Notarization n4) {
		this.n4 = n4;
	}

	public Notarization getN5() {
		return n5;
	}

	public void setN5(Notarization n5) {
		this.n5 = n5;
	}

	public Notarization getN6() {
		return n6;
	}

	public void setN6(Notarization n6) {
		this.n6 = n6;
	}

	public Notarization getN7() {
		return n7;
	}

	public void setN7(Notarization n7) {
		this.n7 = n7;
	}

	public Notarization getN8() {
		return n8;
	}

	public void setN8(Notarization n8) {
		this.n8 = n8;
	}

	/*public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof Notarization)) return false;
		else {
			Notarization notz = (Notarization) obj;
			if (null == this.getId() || null == notz.getId()) return false;
			else return (this.getId().equals(notz.getId()));
		}
	}

	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}*/


	public String toString () {
		return super.toString();
	}
}
